from setuptools import find_packages, setup

setup(name='navi',
      version='0.1',
      packages=find_packages(),
      author='Leonardo Sampaio Ferraz Ribeiro',
      author_email='leo.sampaio.ferraz.ribeiro@gmail.com',
      license='BSD',
      description=("A framework for quickly building better"
                   "and open personal assistants"),
      keywords="navi assistant bot chatbot framework",
      url="https://github.com/leosampaio/navi-framework",
      zip_safe=False,
      package_data={'': ['README.md', 'LICENSE.txt']},
      data_files=[('.', ['README.md', 'LICENSE.txt']),
                  ('navi/resources/sounds', ['navi/resources/sounds/ding.wav',
                                             'navi/resources/sounds/dong.wav',
                                             ])],
      install_requires=['enum34==1.1.6',
                        'PyAudio==0.2.11',
                        'PyDispatcher==2.0.5',
                        'python-telegram-bot==5.3.1',
                        'requests==2.13.0',
                        'snowboy==1.2',
                        'SpeechRecognition==3.6.5',
                        'wit==4.2.0'],
      )
